---
output:
  md_document:
    variant: markdown
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

[//]: <> (Alternative background colours are #002b36 #333 #1E8C45)


## &nbsp; {.hideslideheader data-background="#333"}
<div style="display:table;width:100%;table-layout: fixed;">
  <div class="title-without-logo" style="display:table-cell;width:100%;padding-right:3%;padding-left:3%;vertical-align:middle;">
  From observation to computation? 
  
  Employing social media mining and artificial intelligence to mobilize new citizen science movements.
    
  &nbsp;
    
  &nbsp;
  
  &nbsp;
  </div>
</div>

<div style="display:table;width:100%;table-layout: fixed;">
  <div class="mytitlepage linksection" style="display:table-cell;width:50%;padding-left:3%;vertical-align:bottom;">
  </div>
  
  
  <div class="mytitlepage authorsection" style="display:table-cell;width:50%;padding-right:3%;">
  &nbsp;
  **Stefan Daume**
  
  *Scitingly*
  
  &nbsp;
  
  *ECSA Conference 2018*
  
  *Geneva*
  
  &nbsp;
  
  *04. June 2018*
  
  &nbsp;
  
  *stefan.daume@ecoveillance.org*
  </div>
</div>



## Colophon {.colophon}
**"From observation to computation? - Employing social media mining and artificial intelligence to mobilize new citizen science movements."** by *Stefan Daume*

&nbsp;

Presented at [ECSA Conference 2018](https://www.ecsa-conference.eu/) on 04. June 2018.

&nbsp;

This presentation can be cited using: *doi:...*

&nbsp;

**PRESENTATION DETAILS**

**Author/Affiliation:** Stefan Daume, Scitingly

**Presentation URL:** https://sdaume.github.io/2018-ECSA-Social-Computation

**Presentation Handouts:** https://sdaume.github.io/2018-ECSA-Social-Computation/handouts

**Presentation Source:** [TBD]

**Presentation PDF:** [TBD]

&nbsp;

**CREDITS & LICENSES**

This presentation is delivered with the help of several free and open source tools and libraries. It utilises the [reveal.js](https://revealjs.com/) presentation framework and has been created using [RMarkdown](https://rmarkdown.rstudio.com), [knitr](https://yihui.name/knitr/), [RStudio](https://www.rstudio.com) and [Pandoc](https://pandoc.org/). [highlight.js](https://highlightjs.org) provides syntax highlighting for code sections. PDF and JPG copies of this presentation were generated with [DeckTape](https://github.com/astefanutti/decktape). Please note the respective licenses of these tools and libraries.

&nbsp;

If not noted and attributed otherwise, the contents (text, charts, images) of this presentation are **Copyright &copy; 2018 of the Author** and provided under a *CC BY 4.0* public domain license. 





